type FriendlyBones = {
    [key: string]: string
};

export const FriendlyBones: FriendlyBones = {
    HumanHead: "Head",
    HumanNeck: "Neck",
    HumanLCollarbone: "Left Collarbone", // Disabled
    HumanLUpperarm: "Left Shoulder",
    HumanLForearm1: "Left Elbow",
    HumanLForearm2: "Left Forearm",
    HumanLForearm3: "Left Wrist",
    HumanLPalm: "Left Hand",
    HumanRCollarbone: "Right Collarbone", // Disabled
    HumanRUpperarm: "Right Shoulder",
    HumanRForearm1: "Right Elbow",
    HumanRForearm2: "Right Forearm",
    HumanRForearm3: "Right Wrist",
    HumanRPalm: "Right Hand",
    HumanSpine1: "Stomach",
    HumanSpine2: "Center Mass",
    HumanSpine3: "Chest",
    HumanPelvis: "Groin",
    HumanLThigh1: "Left Hip",
    HumanLThigh2: "Left Thigh 2", // Disabled
    HumanLCalf: "Left Knee",
    HumanLFoot: "Left Ankle",
    HumanLToe: "Left Toe", // Disabled
    HumanRThigh1: "Right Hip",
    HumanRThigh2: "Right Thigh 2", // Disabled
    HumanRCalf: "Right Knee",
    HumanRFoot: "Right Ankle",
    HumanRToe: "Right Toe", // Disabled
    HumanBase: "Base",
};

export const BonesArray = [
    "HumanHead",
    "HumanNeck",
    // "HumanLCollarbone",
    "HumanLUpperarm",
    "HumanLForearm1",
    "HumanLForearm2",
    "HumanLForearm3",
    "HumanLPalm",
    // "HumanRCollarbone",
    "HumanRUpperarm",
    "HumanRForearm1",
    "HumanRForearm2",
    "HumanRForearm3",
    "HumanRPalm",
    "HumanSpine3",
    "HumanSpine2",
    "HumanSpine1",
    "HumanPelvis",
    "HumanLThigh1",
    // "HumanLThigh2",
    "HumanLCalf",
    "HumanLFoot",
    // "HumanLToe",
    "HumanRThigh1",
    // "HumanRThigh2",
    "HumanRCalf",
    "HumanRFoot",
    // "HumanRToe",
    "HumanBase",
];

export const BonesLUT = {
    HumanBase: 0,
    HumanPelvis: 14,
    HumanLThigh1: 15,
    HumanLThigh2: 16,
    HumanLCalf: 17,
    HumanLFoot: 18,
    HumanLToe: 19,
    HumanRThigh1: 20,
    HumanRThigh2: 21,
    HumanRCalf: 22,
    HumanRFoot: 23,
    HumanRToe: 24,
    HumanSpine1: 29,
    HumanSpine2: 36,
    HumanSpine3: 37,
    HumanLCollarbone: 89,
    HumanLUpperarm: 90,
    HumanLForearm1: 91,
    HumanLForearm2: 92,
    HumanLForearm3: 93,
    HumanLPalm: 94,
    HumanRCollarbone: 110,
    HumanRUpperarm: 111,
    HumanRForearm1: 112,
    HumanRForearm2: 113,
    HumanRForearm3: 114,
    HumanRPalm: 115,
    HumanNeck: 132,
    HumanHead: 133,
};
