type FriendlyKeyCodes = {
    [key: string]: string
};

type KeyCodeLUT = {
    [key: string]: number
};

export const FriendlyKeyCodes: FriendlyKeyCodes = {
    None: "Unset",
    Backspace: "Backspace",
    Delete: "DEL",
    Tab: "TAB",
    Return: "Enter",
    Escape: "ESC",
    Space: "Space",
    Keypad0: "Keypad 0",
    Keypad1: "Keypad 1",
    Keypad2: "Keypad 2",
    Keypad3: "Keypad 3",
    Keypad4: "Keypad 4",
    Keypad5: "Keypad 5",
    Keypad6: "Keypad 6",
    Keypad7: "Keypad 7",
    Keypad8: "Keypad 8",
    Keypad9: "Keypad 9",
    KeypadPeriod: "Keypad .",
    KeypadDivide: "Keypad /",
    KeypadMultiply: "Keypad *",
    KeypadMinus: "Keypad -",
    KeypadPlus: "Keypad +",
    KeypadEnter: "Keypad Enter",
    KeypadEquals: "Keypad =",
    UpArrow: "Up Arrow",
    DownArrow: "Down Arrow",
    RightArrow: "Right Arrow",
    LeftArrow: "Left Arrow",
    Insert: "Insert",
    Home: "Home",
    End: "End",
    PageUp: "Page Up",
    PageDown: "Page Down",
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    F13: "F13",
    F14: "F14",
    F15: "F15",
    Alpha0: "0",
    Alpha1: "1",
    Alpha2: "2",
    Alpha3: "3",
    Alpha4: "4",
    Alpha5: "5",
    Alpha6: "6",
    Alpha7: "7",
    Alpha8: "8",
    Alpha9: "9",
    Exclaim: "!",
    DoubleQuote: '"',
    Hash: "#",
    Dollar: "$",
    Percent: "%",
    Ampersand: "&",
    Quote: "'",
    LeftParen: "(",
    RightParen: ")",
    Asterisk: "*",
    Plus: "+",
    Comma: ",",
    Minus: "-",
    Period: ".",
    Slash: "/",
    Colon: ":",
    Semicolon: ";",
    Less: "<",
    Equals: "=",
    Greater: ">",
    Question: "?",
    At: "@",
    LeftBracket: "[",
    Backslash: "\\",
    RightBracket: "]",
    Caret: "^",
    Underscore: "_",
    BackQuote: "`",
    A: "A",
    B: "B",
    C: "C",
    D: "D",
    E: "E",
    F: "F",
    G: "G",
    H: "H",
    I: "I",
    J: "J",
    K: "K",
    L: "L",
    M: "M",
    N: "N",
    O: "O",
    P: "P",
    Q: "Q",
    R: "R",
    S: "S",
    T: "T",
    U: "U",
    V: "V",
    W: "W",
    X: "X",
    Y: "Y",
    Z: "Z",
    LeftCurlyBracket: "{",
    Pipe: "|",
    RightCurlyBracket: "}",
    Tilde: "~",
    Numlock: "Num Lock",
    CapsLock: "CAPS",
    RightShift: "Right Shift",
    LeftShift: "Left Shift",
    RightControl: "Right CTRL",
    LeftControl: "Left CTRL",
    RightAlt: "Right ALT",
    LeftAlt: "Left ALT",
    LeftWindows: "Left WIN",
    RightWindows: "Right WIN",
    Mouse0: "Left Mouse",
    Mouse1: "Right Mouse",
    Mouse2: "Middle Mouse",
    Mouse3: "B. Side Mouse",
    Mouse4: "F. Side Mouse",
    Mouse5: "Mouse 5",
    Mouse6: "Mouse 6",
};

export const KeyCodesArray: string[] = [
    "None",
    "Backspace",
    "Delete",
    "Tab",
    "Return",
    "Escape",
    "Space",
    "Keypad0",
    "Keypad1",
    "Keypad2",
    "Keypad3",
    "Keypad4",
    "Keypad5",
    "Keypad6",
    "Keypad7",
    "Keypad8",
    "Keypad9",
    "KeypadPeriod",
    "KeypadDivide",
    "KeypadMultiply",
    "KeypadMinus",
    "KeypadPlus",
    "KeypadEnter",
    "KeypadEquals",
    "UpArrow",
    "DownArrow",
    "RightArrow",
    "LeftArrow",
    "Insert",
    "Home",
    "End",
    "PageUp",
    "PageDown",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "Alpha0",
    "Alpha1",
    "Alpha2",
    "Alpha3",
    "Alpha4",
    "Alpha5",
    "Alpha6",
    "Alpha7",
    "Alpha8",
    "Alpha9",
    "Exclaim",
    "DoubleQuote",
    "Hash",
    "Dollar",
    "Percent",
    "Ampersand",
    "Quote",
    "LeftParen",
    "RightParen",
    "Asterisk",
    "Plus",
    "Comma",
    "Minus",
    "Period",
    "Slash",
    "Colon",
    "Semicolon",
    "Less",
    "Equals",
    "Greater",
    "Question",
    "At",
    "LeftBracket",
    "Backslash",
    "RightBracket",
    "Caret",
    "Underscore",
    "BackQuote",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "LeftCurlyBracket",
    "Pipe",
    "RightCurlyBracket",
    "Tilde",
    "Numlock",
    "CapsLock",
    "RightShift",
    "LeftShift",
    "RightControl",
    "LeftControl",
    "RightAlt",
    "LeftAlt",
    "LeftWindows",
    "RightWindows",
    "Mouse0",
    "Mouse1",
    "Mouse2",
    "Mouse3",
    "Mouse4",
    "Mouse5",
    "Mouse6",
];

export const KeyCodeLUT: KeyCodeLUT = {
    None: 0,
    Backspace: 8,
    Tab: 9,
    Clear: 12,
    Return: 13,
    Pause: 19,
    Escape: 27,
    Space: 32,
    Exclaim: 33,
    DoubleQuote: 34,
    Hash: 35,
    Dollar: 36,
    Ampersand: 38,
    Quote: 39,
    LeftParen: 40,
    RightParen: 41,
    Asterisk: 42,
    Plus: 43,
    Comma: 44,
    Minus: 45,
    Period: 46,
    Slash: 47,
    Alpha0: 48,
    Alpha1: 49,
    Alpha2: 50,
    Alpha3: 51,
    Alpha4: 52,
    Alpha5: 53,
    Alpha6: 54,
    Alpha7: 55,
    Alpha8: 56,
    Alpha9: 57,
    Colon: 58,
    Semicolon: 59,
    Less: 60,
    Equals: 61,
    Greater: 62,
    Question: 63,
    At: 64,
    LeftBracket: 91,
    Backslash: 92,
    RightBracket: 93,
    Caret: 94,
    Underscore: 95,
    BackQuote: 96,
    A: 97,
    B: 98,
    C: 99,
    D: 100,
    E: 101,
    F: 102,
    G: 103,
    H: 104,
    I: 105,
    J: 106,
    K: 107,
    L: 108,
    M: 109,
    N: 110,
    O: 111,
    P: 112,
    Q: 113,
    R: 114,
    S: 115,
    T: 116,
    U: 117,
    V: 118,
    W: 119,
    X: 120,
    Y: 121,
    Z: 122,
    Delete: 127,
    Keypad0: 256,
    Keypad1: 257,
    Keypad2: 258,
    Keypad3: 259,
    Keypad4: 260,
    Keypad5: 261,
    Keypad6: 262,
    Keypad7: 263,
    Keypad8: 264,
    Keypad9: 265,
    KeypadPeriod: 266,
    KeypadDivide: 267,
    KeypadMultiply: 268,
    KeypadMinus: 269,
    KeypadPlus: 270,
    KeypadEnter: 271,
    KeypadEquals: 272,
    UpArrow: 273,
    DownArrow: 274,
    RightArrow: 275,
    LeftArrow: 276,
    Insert: 277,
    Home: 278,
    End: 279,
    PageUp: 280,
    PageDown: 281,
    F1: 282,
    F2: 283,
    F3: 284,
    F4: 285,
    F5: 286,
    F6: 287,
    F7: 288,
    F8: 289,
    F9: 290,
    F10: 291,
    F11: 292,
    F12: 293,
    F13: 294,
    F14: 295,
    F15: 296,
    Numlock: 300,
    CapsLock: 301,
    ScrollLock: 302,
    RightShift: 303,
    LeftShift: 304,
    RightControl: 305,
    LeftControl: 306,
    RightAlt: 307,
    LeftAlt: 308,
    RightApple: 309,
    RightCommand: 309,
    LeftApple: 310,
    LeftCommand: 310,
    LeftWindows: 311,
    RightWindows: 312,
    AltGr: 313,
    Help: 315,
    Print: 316,
    SysReq: 317,
    Break: 318,
    Menu: 319,
    Mouse0: 323,
    Mouse1: 324,
    Mouse2: 325,
    Mouse3: 326,
    Mouse4: 327,
    Mouse5: 328,
    Mouse6: 329,
};
