import { PlayerType } from "C:/MemoryPackGenerator_TypeScriptOutputDirectory/PlayerType";

export const espSettingsDefaults = [
    {
        id: "espSection_generalSettings",
        name: "General",
        uiType: "section",
    },
    {
        id: "esp_enabled",
        sectionID: "espSection_generalSettings",
        name: "ESP Enabled",
        uiType: "checkbox",
        remote: true,
        value: false,
    },
    {
        id: "esp_displayStyle",
        sectionID: "espSection_generalSettings",
        name: "Display Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Normal",
        info: /*html*/`
            <code>Normal</code> mode creates a resizable and movable window that can be useful if you don't have a fuser.
            <br>
            <code>Fuser</code> mode creates a fullscreen window on the selected <code>Fuser Monitor</code> and is intended only for use with fusers.
        `,
        values: ["Normal", "Fuser"],
    },
    {
        id: "esp_monitor",
        sectionID: "espSection_generalSettings",
        name: "Fuser Monitor",
        uiType: "displayChooser",
        remote: true,
        value: 0,
    },
    {
        id: "espSection_windowProperties",
        name: "Window Properties",
        uiType: "section",
    },
    {
        id: "esp_borderless",
        sectionID: "espSection_windowProperties",
        name: "Borderless",
        uiType: "checkbox",
        remote: true,
        value: false,
    },
    {
        id: "esp_topmost",
        sectionID: "espSection_windowProperties",
        name: "Topmost",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_clickthrough",
        sectionID: "espSection_windowProperties",
        name: "Clickthrough",
        uiType: "checkbox",
        remote: true,
        value: false,
    },
    {
        id: "espSection_Performance",
        name: "Performance",
        uiType: "section",
    },
    {
        id: "esp_showFPS",
        sectionID: "espSection_Performance",
        name: "Show FPS",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_antiAliasing",
        sectionID: "espSection_Performance",
        name: "Anti-aliasing",
        uiType: "checkbox",
        remote: true,
        value: false,
    },
    {
        id: "esp_updateSpeed",
        sectionID: "espSection_Performance",
        name: "ESP Update Speed",
        uiType: "slider",
        remote: true,
        value: 30,
        valueSuffix: "Hz",
        min: 10,
        max: 240,
        step: 1,
    },
    {
        id: "esp_lowLatencyMode",
        sectionID: "espSection_Performance",
        name: "Low Latency Mode",
        uiType: "toggleButtons",
        remote: true,
        value: "Enabled + Boost",
        info: "Reduces ESP latency at the cost of higher CPU and DMA usage.",
        values: ["Disabled", "Enabled", "Enabled + Boost"],
    },
    {
        id: "espSection_Utilities",
        name: "Utilities",
        uiType: "section",
    },
    {
        id: "esp_battleModeEnabled",
        sectionID: "espSection_Utilities",
        name: "Enable Battle Mode",
        uiType: "checkbox",
        remote: true,
        info: "Hides everything except Player and AI bones/boxes.",
        value: false,
    },
    {
        id: "esp_battleModeHotkey",
        sectionID: "espSection_Utilities",
        name: "Battle Mode Hotkey",
        uiType: "hotkey",
        remote: true,
        value: "None",
    },
    {
        id: "esp_smartDeclutterEnabled",
        sectionID: "espSection_Utilities",
        name: "Enable Smart Declutter",
        uiType: "checkbox",
        remote: true,
        info: "Intelligently hides player information (boxes/bones will still render) to declutter the ESP.",
        value: true,
    },
    {
        id: "esp_crosshairStyle",
        sectionID: "espSection_Utilities",
        name: "Crosshair Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Off",
        values: ["Off", "Dot", "Cross"],
    },
    {
        id: "esp_dynamicCrosshair",
        sectionID: "espSection_Utilities",
        name: "Dynamic Crosshair",
        uiType: "checkbox",
        remote: true,
        info: "Hipfire like a pro! This handy option allows you to see where the bullet from your gun will actually land.",
        value: false,
    },
    {
        id: "esp_fakeLaser",
        sectionID: "espSection_Utilities",
        name: "Fake Laser",
        uiType: "checkbox",
        remote: true,
        info: "Draws a line from the barrel of your weapon to the position the bullet will hit.",
        value: false,
    },
    {
        id: "esp_crosshairScale",
        sectionID: "espSection_Utilities",
        name: "Crosshair Scale",
        uiType: "slider",
        remote: true,
        value: 1.0,
        valueSuffix: "x",
        min: 0.1,
        max: 2.0,
        step: 0.1,
    },
    {
        id: "esp_showAimbotFOV",
        sectionID: "espSection_Utilities",
        name: "Show Aimbot FOV",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showSilentAimTarget",
        sectionID: "espSection_Utilities",
        name: "Show Silent Aim Target",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showHeldWeaponInfo",
        sectionID: "espSection_Utilities",
        name: "Show Held Weapon Info",
        uiType: "checkbox",
        remote: true,
        info: "Shows your ammo count, ammo type, and fire mode on the bottom right corner of the ESP.",
        value: true,
    },
    {
        id: "espSection_Players",
        name: "Players",
        uiType: "section",
    },
    {
        id: "esp_playerRenderStyle",
        sectionID: "espSection_Players",
        name: "Render Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Always",
        info: /*html*/`
            <code>Always</code> mode always renders all players even if there is no line of sight.
            <br>
            <code>Visible Only</code> mode only renders a given player if you have line of sight on them.
        `,
        values: ["Always", "Visible Only"],
    },
    {
        id: "esp_maxPlayerRenderDistance",
        sectionID: "espSection_Players",
        name: "Render Distance",
        uiType: "slider",
        info: "The maximum distance a player can be at and still be rendered.",
        remote: true,
        value: 450,
        valueSuffix: "m",
        min: 250,
        max: 1800,
        step: 10,
    },
    {
        id: "esp_playerVisibilityCheckStyle",
        sectionID: "espSection_Players",
        name: "Visibility Check Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Per-Limb",
        info: /*html*/`
            <code>Per-Limb</code> mode highlights only visible limbs.
            <br>
            <code>Whole Body</code> mode shows the whole body as visible if any limb is visible.
            <br>
            <code>Box Only</code> mode uses the bounding box to indicate player visibility.
        `,
        values: ["Per-Limb", "Whole Body", "Box Only"],
    },
    {
        id: "esp_playerBoxStyle",
        sectionID: "espSection_Players",
        name: "Box Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Off",
        values: ["Off", "Corner", "Full"],
    },
    {
        id: "esp_PlayerBoxThickness",
        sectionID: "espSection_Players",
        name: "Box Thickness",
        uiType: "slider",
        remote: true,
        value: 2,
        valueSuffix: "px",
        min: 1,
        max: 8,
        step: 1,
    },
    {
        id: "esp_showPlayerBones",
        sectionID: "espSection_Players",
        name: "Show Bones",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_PlayerBoneThickness",
        sectionID: "espSection_Players",
        name: "Bone Thickness",
        uiType: "slider",
        remote: true,
        value: 2,
        valueSuffix: "px",
        min: 1,
        max: 8,
        step: 1,
    },
    {
        id: "esp_PlayerFontSize",
        sectionID: "espSection_Players",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
    {
        id: "esp_playerStyle_teammate",
        sectionID: "espSection_Players",
        name: "Teammate Style",
        uiType: "playerTypeEspStyle",
        playerType: "human",
        playerID: PlayerType.Teammate,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#00ff00",
            boxColorInvisible: "#00ff00",
            boneColorVisible: "#00ff00",
            boneColorInvisible: "#00ff00",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_enemyPMC",
        sectionID: "espSection_Players",
        name: "Enemy PMC Style",
        uiType: "playerTypeEspStyle",
        playerType: "human",
        playerID: PlayerType.EnemyPMC,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#ff6a6a",
            boxColorInvisible: "#ff0000",
            boneColorVisible: "#ff6a6a",
            boneColorInvisible: "#ff0000",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_playerScav",
        sectionID: "espSection_Players",
        name: "Player Scav Style",
        uiType: "playerTypeEspStyle",
        playerType: "human",
        playerID: PlayerType.PlayerScav,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#ffffa7",
            boxColorInvisible: "#ffff00",
            boneColorVisible: "#ffffa7",
            boneColorInvisible: "#ffff00",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_showPlayersName",
        sectionID: "espSection_Players",
        name: "Show Name",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayersTeamNumber",
        sectionID: "espSection_Players",
        name: "Show Team Number",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayersHandsContents",
        sectionID: "espSection_Players",
        name: "Show Hands Contents",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayersDistance",
        sectionID: "espSection_Players",
        name: "Show Distance",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayerHealth",
        sectionID: "espSection_Players",
        name: "Show Health",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayerLevel",
        sectionID: "espSection_Players",
        name: "Show Level",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showPlayerKD",
        sectionID: "espSection_Players",
        name: "Show K/D",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "espSection_AI",
        name: "AI",
        uiType: "section",
    },
    {
        id: "esp_aiRenderStyle",
        sectionID: "espSection_AI",
        name: "Render Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Always",
        info: /*html*/`
            <code>Always</code> mode always renders all AI even if there is no line of sight.
            <br>
            <code>Visible Only</code> mode only renders a given AI if you have line of sight on them.
        `,
        values: ["Always", "Visible Only"],
    },
    {
        id: "esp_maxAIRenderDistance",
        sectionID: "espSection_AI",
        name: "Render Distance",
        uiType: "slider",
        info: "The maximum distance an AI can be at and still be rendered.",
        remote: true,
        value: 450,
        valueSuffix: "m",
        min: 250,
        max: 1800,
        step: 10,
    },
    {
        id: "esp_aiVisibilityCheckStyle",
        sectionID: "espSection_AI",
        name: "Visibility Check Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Whole Body",
        info: /*html*/`
            <code>Whole Body</code> mode shows the whole body as visible if any limb is visible.
            <br>
            <code>Box Only</code> mode uses the bounding box to indicate AI visibility.
        `,
        values: ["Whole Body", "Box Only"],
    },
    {
        id: "esp_aiBoxStyle",
        sectionID: "espSection_AI",
        name: "Box Style",
        uiType: "toggleButtons",
        remote: true,
        value: "Off",
        values: ["Off", "Corner", "Full"],
    },
    {
        id: "esp_aiBoxThickness",
        sectionID: "espSection_AI",
        name: "Box Thickness",
        uiType: "slider",
        remote: true,
        value: 2,
        valueSuffix: "px",
        min: 1,
        max: 8,
        step: 1,
    },
    {
        id: "esp_showAIBones",
        sectionID: "espSection_AI",
        name: "Show Bones",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_aiBoneThickness",
        sectionID: "espSection_AI",
        name: "Bone Thickness",
        uiType: "slider",
        remote: true,
        value: 2,
        valueSuffix: "px",
        min: 1,
        max: 8,
        step: 1,
    },
    {
        id: "esp_aiFontSize",
        sectionID: "espSection_AI",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
    {
        id: "esp_playerStyle_aiPMC",
        sectionID: "espSection_AI",
        name: "AI PMC Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.AI_PMC,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#ff6a6a",
            boxColorInvisible: "#ff0000",
            boneColorVisible: "#ff6a6a",
            boneColorInvisible: "#ff0000",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_boss",
        sectionID: "espSection_AI",
        name: "Boss Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Boss,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#d272c4",
            boxColorInvisible: "#e617b7",
            boneColorVisible: "#d272c4",
            boneColorInvisible: "#e617b7",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_bossGuard",
        sectionID: "espSection_AI",
        name: "Guard Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.BossGuard,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#c8a2cf",
            boxColorInvisible: "#c975d7",
            boneColorVisible: "#c8a2cf",
            boneColorInvisible: "#c975d7",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_cultistBoss",
        sectionID: "espSection_AI",
        name: "Cultist Boss Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.CultistBoss,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#d272c4",
            boxColorInvisible: "#e617b7",
            boneColorVisible: "#d272c4",
            boneColorInvisible: "#e617b7",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_cultist",
        sectionID: "espSection_AI",
        name: "Cultist Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Cultist,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#d272c4",
            boxColorInvisible: "#e617b7",
            boneColorVisible: "#d272c4",
            boneColorInvisible: "#e617b7",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_raider",
        sectionID: "espSection_AI",
        name: "Raider Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Raider,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#b382d8",
            boxColorInvisible: "#8d17e6",
            boneColorVisible: "#b382d8",
            boneColorInvisible: "#8d17e6",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_rogue",
        sectionID: "espSection_AI",
        name: "Rogue Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Rogue,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#b382d8",
            boxColorInvisible: "#8d17e6",
            boneColorVisible: "#b382d8",
            boneColorInvisible: "#8d17e6",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_scav",
        sectionID: "espSection_AI",
        name: "Scav Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Scav,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#ffb785",
            boxColorInvisible: "#ff6900",
            boneColorVisible: "#ffb785",
            boneColorInvisible: "#ff6900",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_santa",
        sectionID: "espSection_AI",
        name: "Santa Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Santa,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#00ff00",
            boxColorInvisible: "#00ff00",
            boneColorVisible: "#00ff00",
            boneColorInvisible: "#00ff00",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_playerStyle_event",
        sectionID: "espSection_AI",
        name: "Event Style",
        uiType: "playerTypeEspStyle",
        playerType: "ai",
        playerID: PlayerType.Event,
        remote: true,
        value: JSON.stringify({
            boxColorVisible: "#8f8fff",
            boxColorInvisible: "#0000ff",
            boneColorVisible: "#8f8fff",
            boneColorInvisible: "#0000ff",
            fontColor: "#ffffff",
        }),
    },
    {
        id: "esp_showAIName",
        sectionID: "espSection_AI",
        name: "Show Name",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showAIHandsContents",
        sectionID: "espSection_AI",
        name: "Show Hands Contents",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showAIDistance",
        sectionID: "espSection_AI",
        name: "Show Distance",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_showAIHealth",
        sectionID: "espSection_AI",
        name: "Show Health",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "espSection_Items",
        name: "Items",
        uiType: "section",
    },
    {
        id: "esp_showLoot",
        sectionID: "espSection_Items",
        name: "Show Loot",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_maxLootDistance",
        sectionID: "espSection_Items",
        name: "Draw Distance",
        uiType: "slider",
        remote: true,
        value: 100,
        valueSuffix: "m",
        min: 30,
        max: 450,
        step: 10,
    },
    {
        id: "esp_lootFontSize",
        sectionID: "espSection_Items",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
    {
        id: "espSection_Exfil",
        name: "Extractions",
        uiType: "section",
    },
    {
        id: "esp_exfilVisibility",
        sectionID: "espSection_Exfil",
        name: "Visibility",
        uiType: "toggleButtons",
        remote: true,
        value: "Active/Pending",
        values: ["Off", "All", "Active/Pending"],
    },
    {
        id: "esp_maxExtractionDistance",
        sectionID: "espSection_Exfil",
        name: "Draw Distance",
        uiType: "slider",
        remote: true,
        value: 450,
        valueSuffix: "m",
        min: 250,
        max: 1800,
        step: 10,
    },
    {
        id: "esp_exfilFontSize",
        sectionID: "espSection_Exfil",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
    {
        id: "espSection_Grenade",
        name: "Grenades",
        uiType: "section",
    },
    {
        id: "esp_showGrenades",
        sectionID: "espSection_Grenade",
        name: "Show",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_maxGrenadeDistance",
        sectionID: "espSection_Grenade",
        name: "Draw Distance",
        uiType: "slider",
        remote: true,
        value: 150,
        valueSuffix: "m",
        min: 25,
        max: 250,
        step: 5,
    },
    {
        id: "espSection_Claymore",
        name: "Claymores",
        uiType: "section",
    },
    {
        id: "esp_showClaymores",
        sectionID: "espSection_Claymore",
        name: "Show",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_maxClaymoreDistance",
        sectionID: "espSection_Claymore",
        name: "Draw Distance",
        uiType: "slider",
        remote: true,
        value: 50,
        valueSuffix: "m",
        min: 25,
        max: 250,
        step: 5,
    },
    {
        id: "esp_warnClaymoreDistance",
        sectionID: "espSection_Claymore",
        name: "Warning Distance",
        uiType: "slider",
        remote: true,
        value: 20,
        valueSuffix: "m",
        min: 0,
        max: 250,
        step: 5,
    },
    {
        id: "esp_ClaymoreFontSize",
        sectionID: "espSection_Claymore",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
    {
        id: "espSection_Tripwires",
        name: "Tripwires",
        uiType: "section",
    },
    {
        id: "esp_showTripwires",
        sectionID: "espSection_Tripwires",
        name: "Show",
        uiType: "checkbox",
        remote: true,
        value: true,
    },
    {
        id: "esp_maxTripwiresDistance",
        sectionID: "espSection_Tripwires",
        name: "Draw Distance",
        uiType: "slider",
        remote: true,
        value: 50,
        valueSuffix: "m",
        min: 25,
        max: 250,
        step: 5,
    },
    {
        id: "esp_TripwiresFontSize",
        sectionID: "espSection_Tripwires",
        name: "Font Size",
        uiType: "slider",
        remote: true,
        value: 12,
        valueSuffix: "px",
        min: 6,
        max: 24,
        step: 1,
    },
];
