import { PlayerType } from "C:/MemoryPackGenerator_TypeScriptOutputDirectory/PlayerType";

export const appSettingsDefaults = [
    {
        id: "generalTab",
        name: "General",
        uiType: "tab",
    },
    {
        id: "colorsTab",
        name: "Colors",
        uiType: "tab",
    },
    {
        id: "hotkeysTab",
        name: "Hotkeys",
        uiType: "tab",
    },
    {
        id: "player_scale",
        tab: "generalTab",
        name: "Player Scale",
        uiType: "slider",
        value: 1.3,
        min: 0.5,
        max: 2.0,
        step: 0.1,
    },
    {
        id: "loot_scale",
        tab: "generalTab",
        name: "Loot Scale",
        uiType: "slider",
        value: 1.1,
        min: 0.5,
        max: 2.0,
        step: 0.1,
    },
    {
        id: "grenade_scale",
        tab: "generalTab",
        name: "Explosives Scale",
        uiType: "slider",
        value: 1.2,
        min: 0.5,
        max: 2.0,
        step: 0.1,
    },
    {
        id: "exfil_scale",
        tab: "generalTab",
        name: "Exfil Scale",
        uiType: "slider",
        value: 1.1,
        min: 0.5,
        max: 2.0,
        step: 0.1,
    },
    {
        id: "radar_updateRate",
        tab: "generalTab",
        name: "Radar Update Speed",
        uiType: "slider",
        dataType: "int",
        value: 60,
        valueSuffix: "Hz",
        min: 10,
        max: 60,
        step: 1,
    },
    {
        id: "radar_performanceMode",
        tab: "generalTab",
        name: "Performance Mode",
        uiType: "checkbox",
        dataType: "bool",
        value: false,
    },
    {
        id: "playerColor_AimbotLocked",
        tab: "colorsTab",
        name: "Aimbot Target",
        uiType: "colorPicker",
        playerType: PlayerType.AimbotLocked,
        dot: "#000000",
        border: "#000000",
    },
    {
        id: "playerColor_Default",
        tab: "colorsTab",
        name: "Default",
        uiType: "colorPicker",
        playerType: PlayerType.Default,
        dot: "#000000",
        border: "#000000",
    },
    {
        id: "playerColor_LocalPlayer",
        tab: "colorsTab",
        name: "Local Player",
        uiType: "colorPicker",
        playerType: PlayerType.LocalPlayer,
        dot: "#17c8e6",
        border: "#000000",
    },
    {
        id: "playerColor_Teammate",
        tab: "colorsTab",
        name: "Teammate",
        uiType: "colorPicker",
        playerType: PlayerType.Teammate,
        dot: "#17e617",
        border: "#000000",
    },
    {
        id: "playerColor_EnemyPMC",
        tab: "colorsTab",
        name: "Enemy PMC",
        uiType: "colorPicker",
        playerType: PlayerType.EnemyPMC,
        dot: "#ff0000",
        border: "#000000",
    },
    {
        id: "playerColor_PlayerScav",
        tab: "colorsTab",
        name: "Player Scav",
        uiType: "colorPicker",
        playerType: PlayerType.PlayerScav,
        dot: "#feff00",
        border: "#000000",
    },
    {
        id: "playerColor_Scav",
        tab: "colorsTab",
        name: "Scav",
        uiType: "colorPicker",
        playerType: PlayerType.Scav,
        dot: "#ffffff",
        border: "#000000",
    },
    {
        id: "playerColor_ScavBoss",
        tab: "colorsTab",
        name: "Scav Boss",
        uiType: "colorPicker",
        playerType: PlayerType.Boss,
        dot: "#e617c8",
        border: "#000000",
    },
    {
        id: "playerColor_ScavBossGuard",
        tab: "colorsTab",
        name: "Scav Boss Guard",
        uiType: "colorPicker",
        playerType: PlayerType.BossGuard,
        dot: "#c975d7",
        border: "#000000",
    },
    {
        id: "playerColor_Raider",
        tab: "colorsTab",
        name: "Raider",
        uiType: "colorPicker",
        playerType: PlayerType.Raider,
        dot: "#8d17e6",
        border: "#000000",
    },
    {
        id: "playerColor_ExUsec",
        tab: "colorsTab",
        name: "Ex USEC",
        uiType: "colorPicker",
        playerType: PlayerType.Rogue,
        dot: "#8d17e6",
        border: "#000000",
    },
    {
        id: "playerColor_AI_PMC",
        tab: "colorsTab",
        name: "AI PMC",
        uiType: "colorPicker",
        playerType: PlayerType.AI_PMC,
        dot: "#ff0000",
        border: "#000000",
    },
    {
        id: "playerColor_Cultist",
        tab: "colorsTab",
        name: "Cultist",
        uiType: "colorPicker",
        playerType: PlayerType.Cultist,
        dot: "#e617c8",
        border: "#e7ff06",
    },
    {
        id: "playerColor_CultistBoss",
        tab: "colorsTab",
        name: "Cultist Boss",
        uiType: "colorPicker",
        playerType: PlayerType.CultistBoss,
        dot: "#e617c8",
        border: "#ffd900",
    },
    {
        id: "playerColor_Santa",
        tab: "colorsTab",
        name: "Santa",
        uiType: "colorPicker",
        playerType: PlayerType.Santa,
        dot: "#ffffff",
        border: "#feff00",
    },
    {
        id: "playerColor_Event",
        tab: "colorsTab",
        name: "Event",
        uiType: "colorPicker",
        playerType: PlayerType.Event,
        dot: "#8d17e6",
        border: "#000000",
    },
    {
        id: "playerColor_BTR",
        tab: "colorsTab",
        name: "BTR",
        uiType: "colorPicker",
        playerType: PlayerType.BTR,
        dot: "#ffffff",
        border: "#feff00",
    },
    // {
    //     id: "playerColor_Corpse",
    //     tab: "colorsTab",
    //     name: "Corpse",
    //     uiType: "colorPicker",
    //     playerType: PlayerType.Corpse,
    //     dot: "#000000",
    //     border: "#000000",
    // },
];
