name: Build & Deploy Dev

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        cd build
        node deploy.js dev